#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend smartempire007-frontend
        bind *:80
        mode http
        default_backend smartempire007-backend
backend smartempire007-backend
        balance roundrobin
        server 148008-web-01 100.25.37.22 check
        server 148008-web-02 18.234.130.143 check
"
sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
